version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 5000:5000
    networks:
      - appNetwork
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: python 
  db:
    platform: linux
    image: mysql
    container_name: db
    restart: always
    expose:
      - 3306
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: python
    networks:
    - appNetwork  
    volumes:
      - "./sql/studentdata.sql:/docker-entrypoint-initdb.d/init.sql"
      - mysqldata:/var/lib/mysql
    
networks:
  appNetwork:
  
volumes:
  mysqldata: